#!/bin/bash

# Do not forget to cleanup PGDATA dir on making changes

PDATA="/var/lib/postgresql/data/pgdata"
docker run --name postgres-hardinv-win-1 \
    -e PGDATA="$PDATA" \
    -v "D:\data\hardcoded-invaders-1:$PDATA" \
    -p 5432:5432 \
    -d \
    dojo/postgres:hardinv


